# Generated by Django 5.1.5 on 2025-03-15 22:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Permisos",
            new_name="Permiso",
        ),
    ]
