# Generated by Django 5.1.5 on 2025-04-08 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_perfilusuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='ci',
            field=models.PositiveIntegerField(),
        ),
    ]
