# Generated by Django 5.1.5 on 2025-04-08 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_persona_ci'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='ci',
            field=models.CharField(max_length=20),
        ),
    ]
