# Generated by Django 5.1.5 on 2025-04-27 22:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_alter_persona_ci"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="persona",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="persona",
            name="ci",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="persona",
            name="domicilio",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="persona",
            name="fecha_nacimiento",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="persona",
            name="sexo",
            field=models.CharField(
                blank=True,
                choices=[("M", "Masculino"), ("F", "Femenino")],
                max_length=1,
                null=True,
            ),
        ),
    ]
