# Generated by Django 5.1.5 on 2025-05-18 22:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_alter_persona_user_delete_perfilusuario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="persona",
            name="fecha_nacimiento",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="persona",
            name="sexo",
            field=models.CharField(
                choices=[("M", "Masculino"), ("F", "Femenino")],
                default="M",
                max_length=1,
            ),
            preserve_default=False,
        ),
    ]
