# Generated by Django 5.1.5 on 2025-06-16 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificacion',
            old_name='excluir_salas',
            new_name='salas_excluidas',
        ),
    ]
