# Generated by Django 5.1.5 on 2025-05-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educativo', '0002_tutor_email'),
        ('notificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='salas_destinatarias',
            field=models.ManyToManyField(blank=True, related_name='notificaciones', to='educativo.sala'),
        ),
    ]
