# Generated by Django 5.1.5 on 2025-06-16 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0002_rename_excluir_salas_notificacion_salas_excluidas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacion',
            name='fecha_envio',
        ),
        migrations.AddField(
            model_name='notificacion',
            name='fecha',
            field=models.DateField(default='2025-06-16'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notificacion',
            name='hora',
            field=models.TimeField(default='12:00'),
            preserve_default=False,
        ),
    ]
