# Generated by Django 5.1.5 on 2025-06-22 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0003_remove_notificacion_fecha_envio_notificacion_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='enviar_a_todos',
            field=models.BooleanField(default=False),
        ),
    ]
