# Generated by Django 5.1.5 on 2025-05-15 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivos',
            name='archivo',
            field=models.FileField(upload_to=''),
        ),
    ]
