# Generated by Django 5.1.5 on 2025-06-03 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
        ("archivos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="archivos",
            name="persona",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="archivos",
                to="api.persona",
            ),
            preserve_default=False,
        ),
    ]
