# Generated by Django 5.1.5 on 2025-06-16 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('educativo', '0003_tutorinfante'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametrosCobros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anho', models.IntegerField()),
                ('mes_inicio', models.IntegerField()),
                ('mes_fin', models.IntegerField()),
                ('dia_limite_pago', models.IntegerField(default=5)),
                ('monto_cuota', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mora_por_dia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SaldoCuotas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anho', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('nro_cuota', models.IntegerField()),
                ('fecha_generacion', models.DateField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField()),
                ('monto_cuota', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_mora', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.BooleanField(default=False)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('id_infante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='educativo.infante')),
            ],
            options={
                'unique_together': {('id_infante', 'anho', 'mes', 'nro_cuota')},
            },
        ),
    ]
