# Generated by Django 5.1.5 on 2025-06-22 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobrocuotainfante',
            name='monto_cobrado',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='parametroscobros',
            name='monto_cuota',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='parametroscobros',
            name='mora_por_dia',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='saldocuotas',
            name='monto_cuota',
            field=models.IntegerField(),
        ),
    ]
