# Generated by Django 5.1.5 on 2025-06-16 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cobros', '0001_initial'),
        ('educativo', '0003_tutorinfante'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='saldocuotas',
            unique_together={('id_infante', 'anho', 'mes')},
        ),
    ]
