# Generated by Django 5.1.5 on 2025-06-17 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobros', '0002_alter_saldocuotas_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametroscobros',
            name='dias_gracia',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='parametroscobros',
            name='dia_limite_pago',
            field=models.IntegerField(default=31),
        ),
        migrations.CreateModel(
            name='CobroCuotaInfante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cobro', models.DateField()),
                ('monto_cobrado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('cuota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cobros', to='cobros.saldocuotas')),
            ],
        ),
    ]
