# Generated by Django 5.2.1 on 2025-05-30 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnhoLectivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anho', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Infante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ind_alergia', models.CharField(max_length=200)),
                ('ind_intolerancia_lactosa', models.CharField(max_length=200)),
                ('ind_celiaquismo', models.CharField(max_length=200)),
                ('permiso_cambio_panhal', models.CharField(max_length=200)),
                ('permiso_fotos', models.CharField(max_length=200)),
                ('id_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateField()),
                ('id_anho_lectivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educativo.anholectivo')),
                ('id_infante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educativo.infante')),
                ('id_sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educativo.sala')),
                ('id_turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educativo.turno')),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_docente', models.BooleanField(default=False)),
                ('es_estudiante', models.BooleanField(default=False)),
                ('es_funcionario', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('telefono_casa', models.CharField(max_length=50)),
                ('telefono_particular', models.CharField(max_length=50)),
                ('telefono_trabajo', models.CharField(max_length=50)),
                ('nombre_empresa_trabajo', models.CharField(max_length=255)),
                ('direccion_trabajo', models.CharField(max_length=255)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('id_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.persona')),
            ],
        ),
    ]
