# Generated by Django 5.1.5 on 2025-04-08 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educativo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infante',
            name='ind_alergia',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='infante',
            name='ind_celiaquismo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='infante',
            name='ind_intolerancia_lactosa',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='infante',
            name='permiso_cambio_panhal',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='infante',
            name='permiso_fotos',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='es_docente',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='es_estudiante',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='es_funcionario',
            field=models.BooleanField(default=False),
        ),
    ]
