# Generated by Django 5.1.5 on 2025-06-06 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
        ("educativo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="infante",
            name="id_sala",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="educativo.sala",
            ),
        ),
        migrations.AddField(
            model_name="sala",
            name="profesor_encargado",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="salas",
                to="api.persona",
            ),
        ),
    ]
