# Generated by Django 5.1.5 on 2025-05-29 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educativo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
