# Generated by Django 5.1.5 on 2025-06-11 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educativo', '0002_infante_id_sala_sala_profesor_encargado'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorInfante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutores', to='educativo.infante')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorados', to='educativo.tutor')),
            ],
        ),
    ]
