# Generated by Django 5.1.5 on 2025-05-14 21:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("educativo", "0002_alter_infante_ind_alergia_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Inscripcion",
        ),
    ]
