# Generated by Django 5.1.5 on 2025-06-20 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("educativo", "0003_tutorinfante"),
        ("inscripciones", "0004_rename_esta_abierto_periodoinscripcion_activo"),
    ]

    operations = [
        migrations.AddField(
            model_name="infante",
            name="periodo_inscripcion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="inscripciones.periodoinscripcion",
            ),
        ),
        migrations.AddField(
            model_name="sala",
            name="periodo_inscripcion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="inscripciones.periodoinscripcion",
            ),
        ),
        migrations.AddField(
            model_name="tutor",
            name="periodo_inscripcion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="inscripciones.periodoinscripcion",
            ),
        ),
        migrations.AlterField(
            model_name="infante",
            name="id_sala",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="educativo.sala",
            ),
        ),
    ]
