# Generated by Django 5.1.5 on 2025-05-25 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_alter_persona_fecha_nacimiento_alter_persona_sexo"),
        ("educativo", "0003_delete_inscripcion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tutor",
            name="id_persona",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tutor",
                to="api.persona",
            ),
        ),
    ]
