# Generated by Django 5.1.5 on 2025-06-19 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educativo', '0003_tutorinfante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infante',
            name='id_sala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='educativo.sala'),
        ),
    ]
