# Generated by Django 5.1.5 on 2025-05-25 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_alter_persona_fecha_nacimiento_alter_persona_sexo"),
        ("educativo", "0004_alter_tutor_id_persona"),
    ]

    operations = [
        migrations.AlterField(
            model_name="infante",
            name="id_persona",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="infante",
                to="api.persona",
            ),
        ),
        migrations.CreateModel(
            name="TutorInfante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("relacion", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "infante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="infantes_tutores",
                        to="educativo.infante",
                    ),
                ),
                (
                    "tutor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tutores_infantes",
                        to="educativo.tutor",
                    ),
                ),
            ],
            options={
                "unique_together": {("tutor", "infante")},
            },
        ),
    ]
