# Generated by Django 5.1.5 on 2025-06-20 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educativo', '0004_alter_infante_id_sala'),
        ('educativo', '0004_infante_periodo_inscripcion_sala_periodo_inscripcion_and_more'),
    ]

    operations = [
    ]
