# Generated by Django 5.1.5 on 2025-06-20 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "educativo",
            "0004_infante_periodo_inscripcion_sala_periodo_inscripcion_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="sala",
            name="hora_entrada",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sala",
            name="hora_salida",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sala",
            name="limite_infantes",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="sala",
            name="meses",
            field=models.PositiveIntegerField(
                default=0, help_text="Edad máxima permitida en meses para el infante"
            ),
        ),
        migrations.AlterField(
            model_name="infante",
            name="id_sala",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="infantes",
                to="educativo.sala",
            ),
        ),
    ]
