# Generated by Django 5.1.5 on 2025-06-20 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('educativo', '0005_merge_20250620_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferenciaInfante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('infante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educativo.infante')),
                ('sala_destino', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_entrantes', to='educativo.sala')),
                ('sala_origen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_salientes', to='educativo.sala')),
            ],
        ),
        migrations.CreateModel(
            name='TransferenciaProfesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.persona')),
                ('sala_destino', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profesor_entrante', to='educativo.sala')),
                ('sala_origen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profesor_saliente', to='educativo.sala')),
            ],
        ),
    ]
