# Generated by Django 5.1.5 on 2025-06-21 19:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("educativo", "0005_sala_hora_entrada_sala_hora_salida_and_more"),
        ("educativo", "0006_transferenciainfante_transferenciaprofesor"),
    ]

    operations = []
