# Generated by Django 5.1.5 on 2025-06-21 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educativo', '0007_merge_20250620_1813'),
        ('educativo', '0007_merge_20250621_1613'),
    ]

    operations = [
    ]
