# Generated by Django 5.1.5 on 2025-06-22 22:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("educativo", "0008_merge_20250621_1813"),
    ]

    operations = [
        migrations.AddField(
            model_name="infante",
            name="activo",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tutor",
            name="activo",
            field=models.BooleanField(default=False),
        ),
    ]
