# Generated by Django 5.1.5 on 2025-06-07 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("educativo", "0002_infante_id_sala_sala_profesor_encargado"),
    ]

    operations = [
        migrations.CreateModel(
            name="Asistencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_infante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asistencia",
                        to="educativo.infante",
                    ),
                ),
            ],
        ),
    ]
