# Generated by Django 5.1.5 on 2025-06-08 20:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("asistencias", "0001_initial"),
        ("educativo", "0002_infante_id_sala_sala_profesor_encargado"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="asistencia",
            name="estado",
            field=models.CharField(
                choices=[("presente", "Presente"), ("ausente", "Ausente")],
                default="presente",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="asistencia",
            name="fecha",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="asistencia",
            name="hora_entrada",
            field=models.TimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="asistencia",
            name="hora_salida",
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="asistencia",
            name="usuario_auditoria",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="revision_asistencia",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="asistencia",
            unique_together={("id_infante", "fecha")},
        ),
    ]
