# Generated by Django 5.1.5 on 2025-06-08 23:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("asistencias", "0002_asistencia_estado_asistencia_fecha_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asistencia",
            name="hora_salida",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
