# Generated by Django 5.1.5 on 2025-06-01 23:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('educativo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(max_length=250)),
                ('estado', models.BooleanField(default=True)),
                ('id_usuario_aud', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_informe', models.DateField()),
                ('observaciones', models.TextField()),
                ('estado', models.BooleanField(default=False)),
                ('id_infante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='educativo.infante')),
                ('id_usuario_aud', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InformeIndicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ind_logrado', models.BooleanField(default=False)),
                ('id_indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informes.indicador')),
                ('id_informe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicadores', to='informes.informe')),
                ('id_usuario_aud', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TipoInforme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('estado', models.BooleanField(default=True)),
                ('id_usuario_aud', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='informe',
            name='id_tipo_informe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='informes.tipoinforme'),
        ),
        migrations.AddField(
            model_name='indicador',
            name='id_tipo_informe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='informes.tipoinforme'),
        ),
    ]
