# Generated by Django 5.1.5 on 2025-06-15 20:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("informes", "0002_alter_tipoinforme_id_usuario_aud"),
    ]

    operations = [
        migrations.AddField(
            model_name="indicador",
            name="nombre",
            field=models.CharField(default="Prueba", max_length=100),
            preserve_default=False,
        ),
    ]
