# Generated by Django 5.1.5 on 2025-06-01 21:26

import empresas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='logo_reportes',
            field=models.ImageField(blank=True, null=True, upload_to=empresas.models.custom_upload_to),
        ),
    ]
