# Generated by Django 5.1.5 on 2025-05-29 18:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("locales", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="local",
            old_name="id_empresa",
            new_name="empresa",
        ),
    ]
