# Generated by Django 5.1.5 on 2025-05-31 21:39

import django.db.models.deletion
import pagos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("api", "0001_initial"),
        ("locales", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Condicion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.CharField(max_length=30)),
                ("estado", models.BooleanField(default=True)),
                ("cantidad_cuotas", models.PositiveIntegerField(default=1)),
                (
                    "id_usuario_aud",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Proveedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_fantasia", models.CharField(max_length=100)),
                ("ruc", models.CharField(max_length=12, unique=True)),
                ("telefono", models.CharField(max_length=12)),
                ("observaciones", models.TextField(blank=True, null=True)),
                ("estado", models.BooleanField(default=True)),
                (
                    "id_persona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="api.persona"
                    ),
                ),
                (
                    "id_usuario_aud",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ComprobanteProveedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("concepto", models.CharField(max_length=200)),
                (
                    "fecha_comprobante",
                    models.DateField(default=pagos.models.today_date),
                ),
                ("total_comprobante", models.IntegerField()),
                ("numero_comprobante", models.CharField(max_length=15)),
                (
                    "id_local",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="locales.local"
                    ),
                ),
                (
                    "id_usuario_aud",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "id_condicion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="pagos.condicion",
                    ),
                ),
                (
                    "id_proveedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="comprobantes",
                        to="pagos.proveedor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SaldoProveedores",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("monto_cuota", models.IntegerField()),
                ("saldo_cuota", models.IntegerField()),
                ("fecha_pago", models.DateField(blank=True, null=True)),
                ("numero_cuota", models.IntegerField()),
                (
                    "id_comprobante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saldos",
                        to="pagos.comprobanteproveedor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TipoComprobante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.CharField(max_length=30)),
                ("estado", models.BooleanField(default=True)),
                (
                    "id_usuario_aud",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="comprobanteproveedor",
            name="id_tipo_comprobante",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="pagos.tipocomprobante"
            ),
        ),
    ]
