# Generated by Django 5.1.5 on 2025-06-06 01:38

import django.db.models.deletion
import pagos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        ('locales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprobanteProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=200)),
                ('fecha_comprobante', models.DateField(default=pagos.models.today_date)),
                ('total_comprobante', models.IntegerField()),
                ('numero_comprobante', models.CharField(max_length=15)),
                ('id_local', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locales.local')),
                ('id_usuario_aud', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CajaPagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField()),
                ('nro_cuota', models.IntegerField()),
                ('total_pago', models.IntegerField()),
                ('observaciones', models.TextField(max_length=200)),
                ('id_comprobante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pagos.comprobanteproveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Condicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=30)),
                ('estado', models.BooleanField(default=True)),
                ('cantidad_cuotas', models.PositiveIntegerField(default=1)),
                ('id_usuario_aud', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comprobanteproveedor',
            name='id_condicion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pagos.condicion'),
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_fantasia', models.CharField(max_length=100)),
                ('ruc', models.CharField(max_length=12, unique=True)),
                ('telefono', models.CharField(max_length=12)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('id_persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.persona')),
                ('id_usuario_aud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comprobanteproveedor',
            name='id_proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comprobantes', to='pagos.proveedor'),
        ),
        migrations.CreateModel(
            name='SaldoProveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_cuota', models.IntegerField()),
                ('saldo_cuota', models.IntegerField()),
                ('numero_cuota', models.IntegerField()),
                ('id_comprobante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saldos', to='pagos.comprobanteproveedor')),
            ],
        ),
        migrations.CreateModel(
            name='TipoComprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=30)),
                ('estado', models.BooleanField(default=True)),
                ('tipo_saldo', models.CharField(max_length=1)),
                ('id_usuario_aud', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comprobanteproveedor',
            name='id_tipo_comprobante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pagos.tipocomprobante'),
        ),
    ]
