# Generated by Django 5.1.5 on 2025-06-06 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipocomprobante',
            name='tipo_saldo',
            field=models.CharField(choices=[('S', 'Suma'), ('R', 'Resta')], default='S', max_length=1),
        ),
    ]
