# Generated by Django 5.1.5 on 2025-06-06 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_alter_tipocomprobante_tipo_saldo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cajapagos',
            name='id_saldo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='pagos.saldoproveedores'),
            preserve_default=False,
        ),
    ]
