# Generated by Django 5.1.5 on 2025-06-20 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0004_comprobanteproveedor_exentas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobanteproveedor',
            name='timbrado',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
