# Generated by Django 5.1.5 on 2025-05-14 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("educativo", "0003_delete_inscripcion"),
    ]

    operations = [
        migrations.CreateModel(
            name="Inscripcion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("aprobada", "Aprobada"),
                            ("rechazada", "Rechazada"),
                        ],
                        default="pendiente",
                        max_length=10,
                    ),
                ),
                ("fecha_inscripcion", models.DateField(auto_now_add=True)),
                ("observaciones", models.TextField(blank=True, null=True)),
                (
                    "id_infante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inscripciones",
                        to="educativo.infante",
                    ),
                ),
                (
                    "id_tutor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inscripciones",
                        to="educativo.tutor",
                    ),
                ),
            ],
        ),
    ]
