# Generated by Django 5.1.5 on 2025-05-18 22:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("educativo", "0003_delete_inscripcion"),
        ("inscripciones", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="inscripcion",
            unique_together={("id_tutor", "id_infante")},
        ),
    ]
