# Generated by Django 5.1.5 on 2025-06-17 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inscripciones", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PeriodoInscripcion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_inicio", models.DateTimeField()),
                ("fecha_fin", models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name="inscripcion",
            name="periodo_inscripcion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="inscripciones.periodoinscripcion",
            ),
        ),
    ]
