# Generated by Django 5.1.5 on 2025-06-17 20:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inscripciones", "0003_periodoinscripcion_esta_abierto"),
    ]

    operations = [
        migrations.RenameField(
            model_name="periodoinscripcion",
            old_name="esta_abierto",
            new_name="activo",
        ),
    ]
